name: Build EXE for Windows

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # قم بتحديد إصدار Python المطلوب

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # تثبيت المتطلبات

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE using PyInstaller
        run: pyinstaller --onefile --name jefo main.py  # استبدل main.py بالملف الرئيسي لتطبيقك

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jefo-exe
          path: dist/jefo.exe  # مسار الملف التنفيذي الناتج

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/jefo.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
